### ISSUE TITLE
Project 3: tracking_error

### ISSUE THREAD

**Issue by nkrnrnk** [udacity/aitnd-issues#18]
Before the tracking_error function there is a note "Note: When calculating the sample standard deviation, make sure to set the delta degrees of freedom to 0.".

But setting ddof=0 fails the unit test, while ddof=1 passes.

**Comment by cornzyblack** [comment]
Yeah, looks like a mixup. This is incorrect because the default standard deviation function for Numpy is set to **ddof = 0** does not use the unbiased estimator and so,

sd = (√Σ|x - x̄|² /  (n) ) 

to use get the Sample Standard Deviation  which is 

ssd =  (√Σ|x - x̄|² /  (n-1) ) 

we need to set the **ddof = 1**, this uses the unbiased estimator.

or better use pandas DataFrame.std( )  function and that should work.

https://stackoverflow.com/questions/24984178/different-std-in-pandas-vs-numpy

**Comment by e7dud7e** [comment]
Thanks for noting this!  We've updated the project so that it asks for ddof of 1; the unit test should also expect ddof = 1 as well.  Thank you!
