### ISSUE TITLE
Project 4: "Load packages" error

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#69]
Hi! I can see this error, when "Load pacjages" is executed:

RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

Can you please fix it? Thanks!

**Comment by e7dud7e** [comment]
Hi Jevgeni! Thanks for pointing this out.  I was able to re-produce the error that you mentioned, so  I've updated the requirements.txt to install numpy 1.14.5 instead of 1.13.3; After I did "reset data" and installed again, the loading cell no longer gives this error.  Please try "reset data" and let me know if it's good now or if you're still getting an error. Thanks!

**Comment by jevgenitolstouhhov** [comment]
Thank you, now this block runs without errors.
